### ISSUE TITLE
Change License of brew-cask completions to BSD from MIT

### ISSUE THREAD

**Issue by joshka** [joshka/brew-cask-zsh-completions#1]
Mentioning @pstadler as the original author of the completions for brew.

It's a little annoying to have the brew cask licensed MIT and the main Homebrew repo licensed BSD 2 clause, as the script has to include a full copy of the license. Do you mind if I relicense this to the same as Homebrew and drop the MIT license?

**Comment by pstadler** [comment]
I wrote just the cask extension.

**Comment by joshka** [comment]
@pstadler yep that's what I'm talking about - I missed a word in the first sentence :)

**Comment by pstadler** [comment]
Whatever you want. I'm not a lawyer, but this shouldn't be a problem 👍🏻

**Comment by joshka** [comment]
Thanks :)

**Comment by pstadler** [comment]
Would be nice to be listes in the license though.

**Comment by joshka** [comment]
The copyright on the Homebrew repo is:

> Copyright 2009-2016 Homebrew contributors.

So, how about a compromise? I'll relicense the script under the BSD 2 clause license (i.e. remove the MIT license comment) but I'll leave a comment acknowledging authorship in the file?

**Comment by pstadler** [comment]
Never mind. All good 👍🏻
